FROM hub.atomgit.com/library/node:20-buster-slim

WORKDIR '/usr/app'

COPY ./package.json ./
RUN npm install

COPY . .
RUN npm run build

FROM hub.atomgit.com/library/nginx:1.25.2-alpine
EXPOSE 3000
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /usr/app/build /usr/share/nginx/html