name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t claire/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true docker.io/claire/react-test npm test

      - run: docker build -t claire/multi-client ./client
      - run: docker build -t claire/multi-nginx ./nginx
      - run: docker build -t claire/multi-server ./server
      - run: docker build -t claire/multi-worker ./worker
 
      - run: docker tag claire/multi-client 1625191507/multi-client
      - run: docker tag claire/multi-nginx 1625191507/multi-nginx
      - run: docker tag claire/multi-server 1625191507/multi-server
      - run: docker tag claire/multi-worker 1625191507/multi-worker
      - run: docker push 1625191507/multi-client
      - run: docker push 1625191507/multi-nginx
      - run: docker push 1625191507/multi-server
      - run: docker push 1625191507/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to ElasticBeanstalk
        uses: einaregilsson/beanstalk-deploy@v1
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: 'multi-docker'
          environment_name: 'Multi-docker-env'
          existing_bucket_name: elasticbeanstalk-us-east-1-423623837621
          region: 'us-east-1'
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
